### ISSUE TITLE
보관함 수정 기능 구현

### ISSUE THREAD

**Issue by PIYUJIN** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_32_FE#111]
## ✅ Description

보관함 대본 생성, 시간 계산, 발표 연습 수정 기능 구현

## ✔️ TODO
- [ ] 보관함 대본 생성 수정 기능 구현
- [ ] 보관함 시간 계산 수정 기능 구현
- [ ] 보관함 발표 연습 수정 기능 구현
