### ISSUE TITLE
[FIX] 전반적인 에러 FIX & API 연결

### ISSUE THREAD

**Issue by serioushyeon** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_32_FE#139]
## ✅ Description

API 연결 및 테스트하며 생기는 에러나 디자인 수정사항 반영

## ✔️ TODO
- [ ] SignUp 약관 동의 navigate 인자 에러 수정
- [ ] 디자인 수정사항 반영
- [ ] 3.0 API 명세 반영 후 업데이트
- [ ] 에러처리
