### ISSUE TITLE
플로우 컨트롤러 UI간 데이터 연결 

### ISSUE THREAD

**Issue by serioushyeon** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_32_FE#20]
## ✅ Description

플로우 컨트롤러 프래그먼트 간 데이터 관리를 추가
대본 입력 후 문장으로 나누기
## ✔️ TODO
- [x] 프래그먼트 간 데이터 관리 (뷰모델)
- [x] 대본 입력 후 문장으로 나눠서 FlowControllerAddTimeFragment 리사이클러 뷰에 전달
- [x] "숨 고르기 (1초)", "PPT 넘김 (2초)" item 추가 후 문장 연결
- [x] 대본 수정하기
- [x] 대본 커스텀에서 버튼 아이템 클릭 시 삭제 이벤트
