### ISSUE TITLE
Login UI & Development

### ISSUE THREAD

**Issue by PIYUJIN** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_32_FE#21]
## ✅ Description

UID 발급을 통한 로그인 화면 구성 및 기능 구현

## ✔️ TODO
- [x] 로그인 화면 구성
- [x] UID 발급 API 연동
- [x] 기존 기능 UID 전달 기능 추가
