### ISSUE TITLE
Home UI

### ISSUE THREAD

**Issue by PIYUJIN** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_32_FE#27]
## ✅ Description

홈화면 및 보관함 화면 구성

## ✔️ TODO
- [x] 홈화면 화면 구성
- [x] 보관함 화면 구성
- [x] 기능별 보관함 화면 구성
