### ISSUE TITLE
화면 전환 기능 구현

### ISSUE THREAD

**Issue by PIYUJIN** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_32_FE#30]
## ✅ Description

화면 전환 기능 구현 및 수정

## ✔️ TODO
- [ ] 홈 & 보관함 화면 전환 기능 구현
- [ ] 발표 시간 맞춤형 스크립트 생성 화면 전환 기능 수정
- [ ] 단어당 발표 시간 계산기(관리기) 화면 전환 기능 구현
