### ISSUE TITLE
Time Calculator UI

### ISSUE THREAD

**Issue by PIYUJIN** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_32_FE#4]
## ✅ Description

단어당 발표 시간 계산기(관리기) 화면 구성

## ✔️ TODO
- [x] 발표 대본 입력 화면
- [x] 발표 시간 입력 화면
- [x] 빠르기 입력 화면
- [ ] 로딩 화면
- [x] 결과 화면
