### ISSUE TITLE
보관함 기능 구현 각종 에러 수정

### ISSUE THREAD

**Issue by serioushyeon** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_32_FE#50]
## ✅ Description

보관함 기능 구현
## ✔️ TODO
- [x] 보관함 바텀 시트 구현
- [x] 보관함 내용 EdditText 추가
- [x] DestroyView시 뷰모델 초기화 (EditText 값 설정으로 인함)
- [x] 음성파일 있는 것과 없는 것 구분하기
- [x] 빠르기 조절 재생 에러
- [x] EditText 복사 기능
