### ISSUE TITLE
Layout UI Detail

### ISSUE THREAD

**Issue by PIYUJIN** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_32_FE#53]
## ✅ Description

화면 디테일 수정

## ✔️ TODO
- [x] 다크모드 화면 구성
- [x] 시간 선택 number picker 수정
- [x] editText 활성화/비활성화 수정 → 대본 복사 기능 구현
- [x] 앱 아이콘 수정
