### ISSUE TITLE
플로우 컨트롤러 기능 수정 및 UI 반영

### ISSUE THREAD

**Issue by serioushyeon** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_32_FE#57]
## ✅ Description

플로우 컨트롤러 UI 변경 사항 반영 및 스피치 마크 적용하여 정확도 향상, 타이머를 핸들러로 변경하여 성능 향상

## ✔️ TODO
- [x] 플로우 컨트롤러 알고리즘 수정
- [x] 플로우 컨트롤러 속도 조절 추가
- [x] 플로우 컨트롤러 UI 수정
- [x] 플로우 컨트롤러 네비게이션 조정
