### ISSUE TITLE
FlowController Player Development

### ISSUE THREAD

**Issue by serioushyeon** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_32_FE#6]
## ✅ Description
발표 플로우 컨트롤러 결과창, 플레이어 구현, 버튼 드래그 앤 드롭 구현
## ✔️ TODO
- [x] 플레이어 구현
- [x] 리사이클러 뷰 아이템 구현
- [x] 텍스트 하이라이팅 구현
- [x] 텍스트 애니메이션 구현
- [x] 드래그 앤 드롭 시간 추가 ui 구현
