### ISSUE TITLE
로딩창 UI 변경 & 보관함에서 불러오기 UI 변경 & 플로우 컨트롤러 잔 에러 수정

### ISSUE THREAD

**Issue by serioushyeon** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_32_FE#65]
## ✅ Description

로딩 프래그먼트 UI 변경
보관함에서 불러오기 UI 변경
## ✔️ TODO
- [x] 로딩 UI 변경
- [x] 로딩 UI 호출 시 인자 넘기기
- [x] 보관함에서 불러오기 UI 변경
- [x] 플로우 컨트롤러 속도 변경 시 미디어 파일 중복 재생 에러 수정
- [x] 플로우 컨트롤러 문장 분리 시 구분자 개행으로 변경
