### ISSUE TITLE
Script UI

### ISSUE THREAD

**Issue by PIYUJIN** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_32_FE#8]
## ✅ Description

발표시간 맞춤형 스크립트 생성 화면 구성

## ✔️ TODO
- [x] 제목 입력 화면
- [x] 발표 주제 입력 화면
- [x] 발표 시간 입력 화면
- [ ] 로딩 화면
- [x] 스크립트 생성 결과 화면
- [x] 스크립트 수정 화면
