### ISSUE TITLE
보관함 UI

### ISSUE THREAD

**Issue by serioushyeon** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_32_FE#87]
## ✅ Description

보관함 UI 

## ✔️ TODO
- [x] 보관함 목록
- [x] 보관함 검색
- [x] 보관함 필터링
- [x] 보관함 최근 검색 내역
- [x] 보관함 검색 내역 필터링
- [ ] 보관함 검색 내용 하이라이팅
- [ ] 각종 에러 수정
